config/routes.rb
Rails.application.routes.draw do
  root 'qoutes#index'
  get '/qoutes' => 'qoutes#index'
  get '/qoutes/favorites' => 'qoutes#favorites'
  get '/qoutes/qoutes' => 'qoutes#random_qoutes'
  get '/qoutes/new' => 'qoutes#new'
  get '/qoutes/show/:id' => 'qoutes#show'
  post '/qoutes' => 'qoutes#create', as: 'qoute_create'
  get '/qoutes/edit/:id' => 'qoutes#edit'
  patch '/qoutes/:id' => 'qoutes#update', as: 'qoute_update'
  get '/qoutes/save/favorites/:id/:favorites' => 'qoutes#add_favorites', as: 'save_favorites'
  get '/qoutes/remove/favorites/:id/' => 'qoutes#remove_favorites', as: 'remove_favorites'
  delete '/qoutes/:id' => 'qoutes#delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/qoute.rb
class Qoute < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/qoutes_controller.rb
class QoutesController < ApplicationController

  def index
    @qoutes = Qoute.order("created_at ASC")
  end

  def favorites
    @qoutes = Qoute.where(:favorites => true)
  end

  def random_qoutes
    @qoute = Qoute.all.sample
  end 
  def show
    @qoute = Qoute.find(params[:id])
  end

  def new
    @qoute =  Qoute.new
  end

  def create
    @qoute =  Qoute.new(qoute_params)

    if @qoute.save
    redirect_to qoutes_path
    else
      render :new
    end
  end

  def edit
    @qoute = Qoute.find(params[:id])
  end

  def update
    @qoute = Qoute.find(params[:id])
    if @qoute.update(qoute_params)
      redirect_to qoutes_path
    else
      render :edit
    end
  end

  def add_favorites
    @qoute = Qoute.find(params[:id])
    favorites = params[:favorites] == '1' ? false : true
    @qoute.update_attribute(:favorites, favorites)
    redirect_to '/qoutes'
  end

  def remove_favorites
    @qoute = Qoute.find(params[:id])
    if @qoute.update_attribute(:favorites, false)
      redirect_to '/qoutes/favorites'
    end
  end

  def delete
    @qoute = Qoute.find(params[:id])
    @qoute.destroy

    redirect_to root_path
  end

  private

  def qoute_params
    params.require(:qoute).permit(:name, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/qoutes_helper.rb
module QoutesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qoutes App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/b0e17e7f5a.js" crossorigin="anonymous"></script>
    <%= favicon_link_tag asset_path('favicon.ico')%>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   </head>

  <body >
    <div class="containers font-mono">
      <%= yield %>
    </div>
  </body>
</html>

app/views/qoutes/_form.html.erb
<%= form_with scope: :article, url: article_create_path , locale: true do |f| %>

  <div>
    <% if @article.errors.any?%>
      <% @article.errors.full_messages.each do |message|%>
        <p><%=message%></p>
      <%end%>
    <%end%>
  </div>
  
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

   <div>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>

  <div>
   <%= link_to 'Back', '/articles' %>
    <%= f.submit %>
  </div>


  
<% end %>


<div class="table_crud">
  <i class="fas fa-plus-circle"><%= link_to 'Create', '/articles/new' %></i>

  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Body</th>
        <th>Created At</th>
        <th>Updated At</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td><%= article.id %></td>
          <td><%= article.name %></td>
          <td><%= article.body %></td>
          <td><%= article.created_at.to_date %></td>
          <td><%= time_ago_in_words(article.updated_at) %></td>
          <td>
            <i class="fas fa-eye"><%= link_to "Show", "/articles/show/#{article.id}"%></i>
            <i class="fas fa-edit"> <%= link_to 'Edit', "/articles/edit/#{article.id}" %></i>
            <i class="fas fa-trash"><%= link_to 'Delete', "/articles/#{article.id}", method: :delete, data: { confirm: "are you sure?" } %></i>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/qoutes/edit.html.erb
<%# <h1>Edit qoute</h1> %>
<%#= render "form", qoute: @qoute %>


  
<div class="table_crud">

  <%= form_with scope: :qoute, :class => 'mt-72 w-full max-w-sm', url: qoute_update_path , locale: true ,  method: :patch do |f| %>
    <div class="md:flex md:items-center mb-6">
      <div class="md:w-1/3">
        <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
          Author
        </label>
      </div>
      <div class="md:w-2/3">
        <%= f.text_field :name, :class => 'bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500', :placeholder => 'Add your title here' %>
          <% @qoute.errors.full_messages_for(:name).each do |message| %>
            <div style="color:red;"><%= message %></div>
          <% end %>
      </div>
    </div>
    <div class="md:flex md:items-center mb-6">
      <div class="md:w-1/3">
        <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-password">
          Qoutes
        </label>
      </div>
      <div class="md:w-2/3">
        <%= f.text_area :description, :class => 'h-44  bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500', :placeholder => 'Add your qoutes here' %>
          <% @qoute.errors.full_messages_for(:description).each do |message| %>
              <div style="color:red;"><%= message %></div>
          <% end %>
        </div>
    </div>
    <div class="md:flex md:items-center">
      <div class="md:w-1/3"></div>
        <div class="md:w-3/3 flex">
          <button class="shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" type="button">
            <%= link_to 'Back', '/qoutes' %>
          </button>
            <%= f.submit 'Update Qoutes', :class => 'shadow bg-purple-500 ml-12 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded' %>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/qoutes/favorites.html.erb
<div class="table_crud">
  <section class="container mt-8 px-6 py-4 mx-auto">
      <div style="position: fixed; top:0; display:flex; justify-content:space-evenly; width:70%;" class="nav">
      <h1 class="font-serif">Inspirational Qoutes</h1>
      <button class="bg-blue-500 mr-5 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"> <%= link_to '/qoutes' do %> <i class="fas fa-home"> Back to home</i> <% end %></button>
      <button class="bg-blue-500 mr-5 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"><%= link_to '/qoutes/new' do %><i class="fas fa-plus-circle"> Add Qoutes</i><% end %></button>
      <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"> <%= link_to '/qoutes/qoutes' do %> <i class="fas fa-random"> Random Qoutes</i><% end %></button>
    </div>

    <div class="grid gap-6 mb-8 md:grid-cols-1 lg:grid-cols-3">
      <% @qoutes.each do |qoute| %>
      
        <div class="flex items-center p-4  rounded-lg shadow-sm dark:bg-gray-800">
            <div id="body" class="flex flex-col ml-5">
              <h4 id="name" class="text-2xl color-danger font-semibold text-white">
                <%= qoute.name %>
                  <%=link_to remove_favorites_path(qoute.id) do %>
                    <i class="fas <%= qoute.favorites ? 'true' : 'false'%> fa-heart text-red font-bold py-2 px-4 rounded-full" > </i>
                <% end %>
              </h4>
              <h4 id="job" class="text-base text-white mt-2"><%= qoute.description %></p>
              <p id="job" class="text-white mt-2">Updated <%= time_ago_in_words(qoute.updated_at) %> ago.</p>
              <div class="flex mt-5">
                <i class="fas fa-eye m-5 bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-full"> <%= link_to " Show", "/qoutes/show/#{qoute.id}"%></i>
                <i class="fas fa-edit m-5 bg-purple-500 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded-full"> <%= link_to ' Edit', "/qoutes/edit/#{qoute.id}" %></i>
                <i class="fas fa-trash m-5 bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded-full"> <%= link_to ' Delete', "/qoutes/#{qoute.id}", method: :delete, data: { confirm: "are you sure?" } %></i>
              </div>
            </div>

        </div>
      <% end %>

    </div>
  </section>
</div>

app/views/qoutes/index.html.erb
<div class="main_table_crud">
  <section class="container mt-8 px-6 py-4 mx-auto">
    <div style="position: fixed; top:0; display:flex; justify-content:space-evenly; width:70%;" class="nav">
    <h1 class="font-serif">Inspirational Qoutes</h1>
      <button class="bg-blue-500 mr-5 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"><%= link_to '/qoutes/new' do %><i class="fas fa-plus-circle"> Add Qoutesssss</i><% end %></button>
      <button class="bg-blue-500 mr-5 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"><%= link_to '/qoutes/favorites' do %><i class="fas fa-heart"> Favorites</i><% end %></button>
      <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"> <%= link_to '/qoutes/qoutes' do %> <i class="fas fa-random"> Random Qoutes</i><% end %></button>
    </div>

    <div class="grid gap-6 mb-8 md:grid-cols-1 lg:grid-cols-3">
      <% @qoutes.each do |qoute| %>
        <div class="flex items-center p-2  rounded-lg shadow-sm dark:bg-gray-800">
            <div id="body" class="flex flex-col ml-5">
              <h4 id="name" class="text-2xl color-danger font-semibold text-white">
                <%= qoute.name %>
                  <%=link_to "/qoutes/save/favorites/#{qoute.id}/#{qoute.favorites ? '1' : '0'}" do %>
                    <i class="fas <%= qoute.favorites ? 'true' : 'false'%> fa-heart text-red font-bold py-2 px-4 rounded-full" > </i>
                  <% end %>
              </h4>
              <h4 id="job" class="text-base text-white mt-2"><%= qoute.description %></p>
              <p id="job" class="text-white font-bold mt-5"> <% if qoute.created_at == qoute.updated_at %> ― Created at <%= qoute.created_at.to_date %> <% else %> ― Updated <%= time_ago_in_words(qoute.updated_at) %> ago <% end %> </p>
              <div class="flex">
                <%= link_to "/qoutes/show/#{qoute.id}" do %><i class="fas fa-eye m-5 bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-full"> Show</i><% end %>
                <%= link_to "/qoutes/edit/#{qoute.id}" do %><i class="fas fa-edit m-5 bg-purple-500 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded-full"> Edit</i><% end %>
                <%= link_to "/qoutes/#{qoute.id}", method: :delete, data: { confirm: "are you sure?" } do %><i class="fas fa-trash m-5 bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded-full"> Delete</i><% end %>
              </div>
            </div>

        </div>
      <% end %>
    </div>
  </section>
</div>

app/views/qoutes/new.html.erb
<div class="table_crud">

  <%= form_with scope: :qoute, :class => ' mt-72 w-full max-w-sm',  url: qoute_create_path , locale: true do |f| %>
    <div class="md:flex md:items-center mb-6">
      <div class="md:w-1/3">
        <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
          Author
        </label>
      </div>
      <div class="md:w-2/3">
        <%= f.text_field :name, :class => 'bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500', :placeholder => 'Add author here' %>
          <% @qoute.errors.full_messages_for(:name).each do |message| %>
            <div style="color:red;"><%= message %></div>
          <% end %>
      </div>
    </div>
    <div class="md:flex md:items-center mb-6">
      <div class="md:w-1/3">
        <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-password">
          Qoutes
        </label>
      </div>
      <div class="md:w-2/3">
        <%= f.text_area :description, :class => 'bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500 ', :placeholder => 'Add your qoutes here' %>
          <% @qoute.errors.full_messages_for(:description).each do |message| %>
            <div style="color:red;"><%= message %></div>
        <% end %>
      </div>
    </div>

    <div class="md:flex md:items-center">

    <div class="md:w-1/3"></div>
      <div class="md:w-3/3 flex">
        <button class="shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" type="button">
          <%= link_to 'Back', '/qoutes' %>
        </button>
          <%= f.submit 'Save Qoutes', :class => 'shadow bg-purple-500 ml-12 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded' %>
      </div>
    </div>
  <% end %>

</div>

app/views/qoutes/random_qoutes.html.erb
<div class="table_crud_random">
  <section class="container mt-8 px-6 py-4 mx-auto">

    <div style="position: fixed; top:0; display:flex; justify-content:center; width:80%;" class="nav">
      <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"> <%= link_to '/qoutes' do %><i class="fas fa-home"> Back to home</i><% end %></button>
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full ml-5"> <%= link_to '/qoutes/qoutes' do %> <i class="fas fa-random"> Random Qoutes</i><% end %></button>
    </div>

    <div id="body" class="flex flex-col ml-5" style="justify-content:center; text-align:center; align-items:center;">
      <h4 id="name" class="text-5xl color-danger font-semibold text-white">
        <%= @qoute.name %>
          <%=link_to "/qoutes/save/favorites/#{@qoute.id}/#{@qoute.favorites ? '1' : '0'}" do %>
            <i class="fas <%= @qoute.favorites == true ? 'true' : 'false'%> fa-heart text-red font-bold py-2 px-4 rounded-full" > </i>
          <% end %>
      </h4>
      <h4 id="job" class="text-3xl text-white mt-2" style="width:50%;"><%= @qoute.description %></p>
    </div>

  </section>
</div>

app/views/qoutes/show.html.erb
<div class="table_crud">
  <section class="container mt-8 px-6 py-4 mx-auto">

    <div id="body" class="flex flex-col ml-5" style="justify-content:center; text-align:center; align-items:center;">
      <h4 id="name" class="text-5xl color-danger font-semibold text-white"><%= @qoute.name %></h4>
      <h4 id="job" class=" text-3xl text-base text-white mt-2" style="width:50%;"><%= @qoute.description %></h4>
      <p id="job" class="text-white mt-2">Created At <%= @qoute.created_at.to_date %></p>
      <p id="job" class="text-white mt-2">Updated <%= time_ago_in_words(@qoute.updated_at) %> ago.</p>
      <div class="flex mt-5" style="justify-content:space-evenly; text-align:center; align-items:center;">
        <i class=" m-5 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full fas fa-home"> <%= link_to " Back", "/qoutes"%></i>
        <i class="fas fa-edit m-5 bg-purple-500 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded-full"> <%= link_to ' Edit', "/qoutes/edit/#{@qoute.id}" %></i>
        <i class="fas fa-trash m-5 bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded-full"> <%= link_to ' Delete', "/qoutes/#{@qoute.id}", method: :delete, data: { confirm: "are you sure?" } %></i>
      </div>
    </div>

  </section>
</div>